import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import barber from "./barber.ico";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Connect Barber",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <head>
                <link rel="icon" type="image/svg+xml" href="./barber.svg" />
            </head>
            <body className={`${inter.className} dark`}>{children}</body>
        </html>
    );
}
