import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import Footer from "./_components/footer";
import AuthProvider from "./_providers/auth";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Connect Barber",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={`${inter.className} dark`}>
                <AuthProvider>
                    {children}
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
